title: Michalchuk
description: Mechanical Reactivity of Molecular Materials
author: Adam Michalchuk
avatar: /logo.png
email: adam.michalchuk(at)bam.de

plugins:
  - jekyll-theme-hamilton
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton

#Layout
skin: daylight
show_excerpts: false

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: amichalchuk
  card: summary
logo: logo.png
social:
  name: amichalchuk
  links:
    - https://twitter.com/amichalchuk
    - https://www.researchgate.net/profile/Adam-Michalchuk
    - https://scholar.google.com/citations?user=JQE8NLIAAAAJ&hl=en&oi=ao
google_site_verification: 
lang: en
